package confluence

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"sort"
	"strconv"
	"strings"
)

func digestBytes(data []byte) string {
	sum := sha256.Sum256(data)
	return "sha256:" + hex.EncodeToString(sum[:])
}

func canonicalGraph(graph SemanticGraph) SemanticGraph {
	result := SemanticGraph{
		Nodes: append([]GraphNode(nil), graph.Nodes...),
		Edges: append([]GraphEdge(nil), graph.Edges...),
	}
	sort.Slice(result.Nodes, func(i, j int) bool {
		if result.Nodes[i].ID == result.Nodes[j].ID {
			return result.Nodes[i].Kind < result.Nodes[j].Kind
		}
		return result.Nodes[i].ID < result.Nodes[j].ID
	})
	sort.Slice(result.Edges, func(i, j int) bool {
		left := result.Edges[i].From + "\x00" + result.Edges[i].To + "\x00" + result.Edges[i].Kind
		right := result.Edges[j].From + "\x00" + result.Edges[j].To + "\x00" + result.Edges[j].Kind
		return left < right
	})
	return result
}

func sortedStrings(values []string) []string {
	result := append([]string(nil), values...)
	sort.Strings(result)
	return result
}

func canonicalIR(input SourceInput, spec Spec, state map[string]string, operations []Operation) SemanticIR {
	ids := make([]string, 0, len(operations))
	for _, operation := range operations {
		ids = append(ids, operation.ID)
	}
	return SemanticIR{
		Schema:   "gooo/semantic-ir/v1",
		SourceID: input.SourceID,
		CaseID:   input.CaseID,
		Contract: input.Contract,
		Toolchain: input.Toolchain,
		Runner:   input.Runner,
		Graph:    canonicalGraph(spec.SemanticGraph),
		State:    state,
		Applied:  sortedStrings(ids),
	}
}

func marshalCanonical(value any) ([]byte, error) {
	return json.Marshal(value)
}

func generatedSource(state map[string]string) string {
	paths := make([]string, 0, len(state))
	for path := range state {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	var builder strings.Builder
	builder.WriteString("// Code generated by Gooo semantic confluence evaluation; DO NOT EDIT.\n")
	builder.WriteString("package generated\n\n")
	builder.WriteString("var Fields = map[string]string{\n")
	for _, path := range paths {
		builder.WriteString("\t")
		builder.WriteString(strconv.Quote(path))
		builder.WriteString(": ")
		builder.WriteString(strconv.Quote(state[path]))
		builder.WriteString(",\n")
	}
	builder.WriteString("}\n")
	return builder.String()
}

func provenance(operations []Operation) []ProvenanceEntry {
	entries := make([]ProvenanceEntry, 0)
	for _, operation := range operations {
		for _, patch := range operation.Patches {
			entries = append(entries, ProvenanceEntry{
				Operation: operation.ID,
				Path:      patch.Path,
				Value:     patch.Value,
				Authority: operation.Authority,
			})
		}
	}
	sort.Slice(entries, func(i, j int) bool {
		left := entries[i].Operation + "\x00" + entries[i].Path + "\x00" + entries[i].Value
		right := entries[j].Operation + "\x00" + entries[j].Path + "\x00" + entries[j].Value
		return left < right
	})
	return entries
}

func formatDigest(value any) (string, []byte, error) {
	data, err := marshalCanonical(value)
	if err != nil {
		return "", nil, err
	}
	return digestBytes(data), data, nil
}

func pathWithin(path, prefix string) bool {
	return path == prefix || strings.HasPrefix(path, prefix+".")
}

func requiredOperationFieldMissing(operation Operation, field string) bool {
	switch field {
	case "scope":
		return len(operation.Scope) == 0
	case "authority":
		return operation.Authority == ""
	case "patches":
		return len(operation.Patches) == 0
	default:
		return false
	}
}

func operationMap(operations []Operation) map[string]Operation {
	result := make(map[string]Operation, len(operations))
	for _, operation := range operations {
		result[operation.ID] = operation
	}
	return result
}

func operationConflict(spec Spec, left, right Operation) (string, bool) {
	sharedPath := false
	for _, leftPatch := range left.Patches {
		for _, rightPatch := range right.Patches {
			if leftPatch.Path == rightPatch.Path {
				sharedPath = true
			}
		}
	}
	if !sharedPath {
		return "", false
	}
	for _, pair := range spec.Authorities.ConflictPairs {
		if len(pair) != 2 {
			continue
		}
		if (left.Authority == pair[0] && right.Authority == pair[1]) ||
			(left.Authority == pair[1] && right.Authority == pair[0]) {
			return "authority pair is explicitly incompatible", true
		}
	}
	return "", false
}
